name: Deploy to VDS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

#    - name: Add SSH Key
#      run: |
#        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
#        chmod 600 ~/.ssh/id_rsa
#
#    - name: Add server to known_hosts
#      run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to VDS
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP << EOF
        cd root/jarvis/esp
        git pull
        pip install -r root/jarvis/esp/esp-Jarvis-Server/requirements.txt
        python root/jarvis/esp/esp-Jarvis-Server/main.py
        EOF