name: Deploy to VDS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to VDS
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        ssh -i ~/.ssh/id_rsa $SSH_USER@$SERVER_IP << EOF
        cd jarvis/esp
        git pull
        pip install -r esp-Jarvis-Server/requirements.txt
        python esp-Jarvis-Server/main.py
        EOF