name: Deploy to VDS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Deploy to VDS
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP << EOF
        cd jarvis/esp/esp-Jarvis-Server
        git pull
        if [ ! -d "venv" ]; then
            python3.11 -m venv venv
        fi
        source venv/bin/activate
        pip install -r requirements.txt
        python main.py
        deactivate
        EOF